enabled_locales: ["en"]
static_pages:
  rails_contact: "http://www.railstutorial.org/contact"
  screencasts: "http://screencasts.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  rails: "http://www.railstutorial.org/"
  ror: "http://rubyonrails.org/"
  michael: "http://www.michaelhartl.com/"
  news_rails: "http://news.railstutorial.org/"
users:
  size: 80
  name_max: 50
  email_max: 255
  pass_min: 6
  gravatar: "http://gravatar.com/emails"
  size_user: 50
controller:
  per_page: 20
